# FROM node:18-alpine

# LABEL version="1.0" descritpion="Node image prod"

# WORKDIR /appecomme/src/app

# COPY package*.json ./

# RUN npm install  pm2 -g --only=production

# COPY . .

# RUN npm run build

# EXPOSE 3000

# CMD [ "npm", "run","prod" ]


# FROM node:lts-alpine
# WORKDIR /appecomme/src/app
# COPY package*.json ./
# RUN npm install 
# RUN npm install glob rimraf
# COPY . .
# RUN npm run build



# FROM node:lts-alpine

# WORKDIR /appecomme/src/app
# # COPY package.json ./
# RUN npm install pm2 -g --only=production
# # COPY . .

# COPY --from=development  /appecomme/src/app ./

# CMD npm run start:prod


#-------------------- GOOD ONE , NEST ERROR----------------------------------------

FROM node:18-alpine  As build

LABEL version="1.0" descritpion="Node image prod"

WORKDIR /appecomme/src/app



COPY ./package.json ./

RUN npm install 

COPY . .

RUN npm run build

RUN npm ci --only=production && npm cache clean --force



FROM node:18-alpine as production

LABEL version="1.0" descritpion="Node image prod"

# WORKDIR /appecomme/src/app

# COPY package*.json ./

# RUN npm install  pm2 -g  --only=production

# COPY --from=build /appecomme/src/app/dist ./dist

# COPY --from=build /appecomme/src/app/package.json .

COPY  --from=build /appecomme/src/app/node_modules ./node_modules
COPY  --from=build /appecomme/src/app/dist ./dist

# RUN mkdir -p /appecomme/src/app/images  
RUN npm install pm2 -g

EXPOSE 4600

CMD [ "pm2-runtime", "dist/main.js" ]




#*******************************--------------------------



###################
# BUILD FOR PRODUCTION
###################

# FROM node:18-alpine As build

# WORKDIR /usr/src/app

# COPY --chown=node:node package*.json ./

# COPY --chown=node:node --from=development /usr/src/app/node_modules ./node_modules

# COPY --chown=node:node . .

# RUN npm run build

# ENV NODE_ENV production

# RUN npm ci --only=production && npm cache clean --force

# USER node

# ###################
# # PRODUCTION
# ###################

# FROM node:18-alpine As production

# COPY --chown=node:node --from=build /usr/src/app/node_modules ./node_modules
# COPY --chown=node:node --from=build /usr/src/app/dist ./dist

# CMD [ "node", "dist/main.js" ]

