version: '2.17'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 4600:4600
    volumes:
      - .:/appecomme/src/app
      - /appecomme/src/app/node_modules/
    command: npm run start:debug
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/db_app_ecommerce
      NODE_ENV: development
      PORT: 4600

  postgres:
    image: postgres:14.4
    ports:
      - '35000:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_app_ecommerce

  postgres_admin:
    image: dpage/pgadmin4:latest
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80
